---
apiVersion: v1
kind: ConfigMap
metadata:
  name: provider-siglet-config
  namespace: edc
data:
  siglet.toml: |
    [token]
    server_secret = "93d22865c1b0695d3caa1ac5ba648b88942aaeee3b05ba4aff2efc87e2cd1944"
    [storage_backend]
    type = "postgres-vault"
    url = "postgresql://psiglet:psiglet@postgres:5432/providersigletdb"
    [[transfer_types]]
    transfer_type = "HttpData-PULL"
    endpoint_type = "HTTP"
    endpoint = "http://provider.localhost/api/dp/data/download"
    token_source = "provider"
    [signaling_auth]
    mode = "disabled"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-siglet-config
  namespace: edc
data:
  siglet.toml: |
    [token]
    server_secret = "93d22865c1b0695d3caa1ac5ba648b88942aaeee3b05ba4aff2efc87e2cd1944"
    [storage_backend]
    type = "postgres-vault"
    url = "postgresql://csiglet:csiglet@postgres:5432/consumersigletdb"
    [[transfer_types]]
    transfer_type = "HttpData-PULL"
    endpoint_type = "HTTP"
    endpoint = "http://consumer.localhost/api/dp/data/download"
    token_source = "provider"
    [signaling_auth]
    mode = "disabled"

# Vault Agent configuration for Siglet
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config-siglet
  namespace: edc
data:
  vault-agent-config.hcl: |
    pid_file = "/tmp/vault-agent.pid"

    vault {
      address = "http://vault:8200"
    }

    auto_auth {
      method {
        type = "kubernetes"

        config = {
          role = "siglet-role"
        }
      }

      sink {
        type = "file"
        config = {
          path = "/vault/secrets/.vault-token"
          mode = 0644
        }
      }
    }
