---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
  namespace: edc

data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.edc.svc.cluster.local:4318"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://prometheus.edc.svc.cluster.local:9090/api/v1/otlp/v1/metrics"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://loki.edc.svc.cluster.local:3100/otlp/v1/logs"